/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { Types } from "mongoose";

export interface IAddContact {
  email: string;
  name: string;
  phone: string;
  favorite?: boolean;

  owner?: Types.ObjectId;
}

export interface IUpdateFavorite {
  favorite: boolean;
}

export interface IGetAll extends Document {
  _id?: Types.ObjectId;
  owner?: Types.ObjectId;
  name: string;
  email: string;
  phone: string;
  favorite?: boolean;
}
// export interface IRequest extends Document {
//   user: IGetAll;
//   query?: any;
// }

export interface IGetByID extends Document {
  name: string;
  email: string;
  phone: string;
  favorite?: boolean;
}
