/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IAddContact {
  email: string;
  favorite?: boolean;
  name: string;
  phone: string;
  owner?: any;
}

export interface IUpdateFavorite {
  favorite: boolean;
}
